package com.echo.hotpatch;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Toast;

import com.android.tools.fd.runtime.IncrementalChange;
import com.android.tools.fd.runtime.IncrementalClassLoader;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

// TODO
// just like the instant-run in Android Studio, need a plugin to
// 1. insert the $change field to every class
// 2. insert patch proxy code to every method


public class MainActivity extends AppCompatActivity {
    // TODO this field should be generated by gradle plugin
    public static volatile transient IncrementalChange $change;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // TODO init in the application
        // need some strategy to load patch
        List<String> dexes = new ArrayList<>();
        String path = getFilesDir().getAbsolutePath() + File.separator + "patch" + File.separator;
        dexes.add(path + "patch.dex");
        IncrementalClassLoader.inject(getClassLoader(), null, getCacheDir().getAbsolutePath(), dexes);
    }

    public void onTest(View view) {
        // TODO the following lines show be generated by gradle plugin
        // the following lines are just for playing
        IncrementalChange change = $change;
        if (change != null) {
            change.access$dispatch("onTest.(Landroid/view/View;)V", new Object[]{this, view});
            return;
        }
        // end

        Toast.makeText(this, "hello not patched", Toast.LENGTH_SHORT).show();
    }

    public void onPatch(View view) {
        Patcher.patch();
        Toast.makeText(this, "patch finished", Toast.LENGTH_SHORT).show();
    }
}
